name: Conventional Commits Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conventional-commits-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Verify commits
        run: bash scripts/check-commits.sh
